# 💖 Sponsors and Backers
# KoBar is an open-source project. If you find this utility sidebar helpful, consider supporting its ongoing development!

ko_fi: eedali
patreon: kobarproject
custom: ["https://www.paypal.me/ekremedali"]
open_collective: kobar
