## 💖 Sponsors and Backers

KoBar is an open-source project. If you find this utility sidebar helpful, consider supporting its ongoing development!

ko_fi: https://ko-fi.com/eedali
custom: Paypal ['https://www.paypal.me/ekremedali']
